version: "2.0"
services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/starwars
      - SPRING_DATA_MONGODB_URI=mongodb://matheus:matheus123@ds259207.mlab.com:59207/base_matheus
    container_name: star-wars-api
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net
  mongo:
    image: mongo:3.4
    container_name: star-wars-mongodb
    ports:
#      - 27017:27017
      - 27017:59207
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge